### PR TITLE
Paddling categories

### PR DESCRIPTION
**Pull request by treestryder**
Please consider adding these 3 new categories (routes, hazards and amenities) for human powered boating; canoe, kayak, standup paddleboards, row boats, pedalboats, etc. Guidance on the OpenStreetMap Wiki, states that the generic term/key/tag is "canoe".
* https://wiki.openstreetmap.org/wiki/Key:canoe
* https://wiki.openstreetmap.org/wiki/Tag:route%3Dcanoe

When naming these new categories I went with the term "paddling" as it seemed to be the most inclusive verb that matched the current practice on OpenStreetBrowser (cycling, hiking, climbing, etc).

To see an example of this work, here is a well mapped area, using my development repository:
https://openstreetbrowser.org/#map=17/42.74361/-84.54936&categories=treestryder./paddlecraft/paddling_amenities,treestryder./paddlecraft/paddling_hazards,treestryder./paddlecraft/paddling_routes

### CODE REVIEW

**Comment by plepe** [comment]
That's awesome, I like it!

One comment though: I think, the transparent markers are confusing, because they are difficult to see, especially when they overlap each other. I would consider some kind of background color, maybe white?

In general, I prefer icons from the [other icon sets - see docu](https://github.com/plepe/OpenStreetBrowser/blob/master/doc/Icons.md) (Font Awesome, Maki, Temaki), because of their contrast. You could check, if you can find some.

**Comment by plepe** [comment]
I'm so sorry, it was my fault. I recently added, that the 'fill' parameter is handled, but I made a mistake. It should work again as expected.

In case you ever need it: if you set 'fill' to false, the marker will not be filled.

**Comment by Hufkratzer** [comment]
The background colors work again. Thanks.

**Comment by treestryder** [comment]
@plepe , thanks to your nudge, your instructions, your bug fix, the link to the full and searchable Font Awesome Free icon set and everything else... I think it looks much nicer. I'm ready for another code review (and, I see now I should have converted this to a draft when I wasn't).

**Comment by plepe** [comment]
Very nice :-) I will merge the pull request in the evening (central european time).

Adding an additional sub-category to "Leisure, Sport and Shopping" brings me back to #34 - I would like to do this soon.

**Comment by plepe** [comment]
Okay, the categories are now online! I included them in the 'Outdoor' section. I moved the names to the language file, so they can be translated by the translation system (69c9b5580be162c1b490080df7ad14d8f886ebd6).

Would you want to create a nice screenshot and a text for the announcement?

**Comment by treestryder** [comment]
Thank you! I am really excited. It is so hard to share OpenStreetMap data with people in a "just use this one user-friendly app" way. I have wanted to create this pull request, ever since I first heard about OpenStreetBrowser, not long after its creation. I'm also excited to show this off in just a little while, the Michigan OpenStreetMap meetup is tonight at 7 PM (Eastern).

Regarding the categories. Sorry I did not chime in earlier. I had already found it interesting that walking and (road) cycling are separate from climbing and mountain biking (cycling), and now paddling. I do all of those things for different reasons. None of them for "exercise". Usually, it is just how I chose to get to a place or for fun. Point being, you can leave it for now and I will chime in on the other conversation. I consider all of them forms of transportation, so that name works pretty well. And no matter the name, they are much harder to find when they are hidden beneath more than one branch.

**Pull request merged**
