### PR TITLE
Categories FR update

### PR DESCRIPTION
**Pull request by Cybereric**
I don't understand very well the difference between "Electric Power" and "Power Routes"  I have electric lines in the two categories.
I don't find the "Christmas" category

### CODE REVIEW

**Comment by plepe** [comment]
Yes, I guess the distinction is not easy - Electric Power are the physical infrastructure, like rails for Railway. Power routes are the logical infrastructure, like the tram routes which actually use this infrastructure:
* Electric Power: https://wiki.openstreetmap.org/wiki/Tag:power%3Dline
* Power routes: https://wiki.openstreetmap.org/wiki/Proposed_features/Power_routing_proposal

You can find the Christmas category under "Special" -> https://www.openstreetbrowser.org/#categories=xmas

**Comment by plepe** [comment]
Yes, I guess the distinction is not easy - Electric Power are the physical infrastructure, like rails for Railway. Power routes are the logical infrastructure, like the tram routes which actually use this infrastructure:
* Electric Power: https://wiki.openstreetmap.org/wiki/Tag:power%3Dline
* Power routes: https://wiki.openstreetmap.org/wiki/Proposed_features/Power_routing_proposal

You can find the Christmas category under "Special" -> https://www.openstreetbrowser.org/#categories=xmas

**Comment by Cybereric** [comment]
About "Electric things" ;-)
That's what I understood. So why "Electric power" when speaking of "Electric (power) lines" ?
"Electric Power" is that >>> https://en.wikipedia.org/wiki/Electric_power
So if it concerns ["Electric power lines](https://en.wikipedia.org/wiki/Overhead_power_line)" for  "[Electric power transmission](https://en.wikipedia.org/wiki/Electric_power_transmission)" no problem 
I'll translate by "Lignes électriques" 
And for "routes" by "Réseau (network) électrique"
Don't bother with that. 
I will check later what objects it concerns and I would change that if needed

Concerning "Christmas" it's not for the use ;-) but for the translation !
I don't find "Christmas" in the categories >>> https://github.com/plepe/openstreetbrowser-categories-main/blob/master/lang/fr.json

**Comment by plepe** [comment]
Oh, you are right. Just updated the language files, so you can now translate 'xmas' and 'swimming-bathing'.

Electric power does not only contain lines (sorry, I was not exact), but also generators, transformers, ...
see https://github.com/plepe/openstreetbrowser-categories-main/blob/master/electric_power.json

**Comment by plepe** [comment]
Sorry, pushed it to the wrong repo. Now the updated files are online.

**Pull request merged**
